[package]
name = "composer"
version = "0.2.0"
authors = ["Christoph Wurst <christoph@winzerhof-wurst.at>"]
description = "Rust wrapper around php's composer to install php dependencies"
edition = "2018"

[dependencies]
failure = "0.1"
